version: '3'

services:
  mysql:
    image: mysql:8.0.25
    restart: always
    container_name: mysql-container
    environment: MYSQL_ROOT_PASSWORD=alticast#
      MYSQL_DATABASE=root
    ports:
      - '3306:3306'
